# Generated by Django 4.1 on 2023-01-17 16:46

import authy.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Adminprofile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=100, null=True)),
                ("url", models.CharField(blank=True, max_length=80, null=True)),
                (
                    "profile_info",
                    models.TextField(blank=True, max_length=100, null=True),
                ),
                ("created", models.DateField(auto_now_add=True)),
                (
                    "picture",
                    models.ImageField(
                        upload_to=authy.models.user_directory_path_profile
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
